[[constraint]]
  name = "github.com/hashicorp/go-retryablehttp"
  branch = "master"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/logrusorgru/aurora"
  branch = "master"
[[constraint]]
  branch = "master"
  name = "github.com/aybabtme/rgbterm"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.4"
