---
version: 2
jobs:
  release:
    docker:
      - image: timberio/cli-builder:1.0.1
    working_directory: /go/src/github.com/timberio/cli
    steps:
      - checkout
      - run:
          name: Publish Release
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              make release
            else
              echo "Not running a release tag"
            fi

workflows:
  version: 2
  build:
    jobs:
      - release:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/