---
version: 2
jobs:
  # No tests currently
  # test:
  #   docker:
  #     - image: timberio/cli-builder:1.0.0
  #   working_directory: /go/src/github.com/timberio/cli
  #   environment:
  #     TEST_RESULTS: /tmp/test-results
  #   steps:
  #     - checkout
  #     - run:
  #         name: Setup Test Results Directory
  #         command: |
  #           mkdir -p ${TEST_RESULTS}
  #     - run:
  #         name: Run Tests
  #         command: |
  #           trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
  #           make test | tee ${TEST_RESULTS}/go-test.out
  #     - store_test_results:
  #         path: /tmp/test-results
  release:
    docker:
      - image: timberio/cli-builder:1.0.0
    working_directory: /go/src/github.com/timberio/cli
    steps:
      - checkout
      - run:
          name: Publish Release
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              make release
            else
              echo "Not running a release tag"
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/